### ISSUE TITLE
ToDos

### ISSUE THREAD

**Issue by gkiar** [Upward-Spiral-Science/Syllabus#1]
- [x] Add Greg to the organization
- [x] Fix mailto link for greg
- [x] projects due nlt 3pm on what day of the week?
- [x] under github bullet 'options' is misspelled
- [x] clarify if all students should submit independent reports and code or if 1 copy per group is required? If the latter, we should add a private peer evaluation weighting formula so someone doesn't get carried/a group doesn't get punished for carrying, imo.

**Comment by jovo** [comment]
re: grading, i'm open to your proposed system, i don't quite understand it.

**Comment by gkiar** [comment]
Each week the students will also fill out an anonymous google form in which
they rate from 1-10 themselves and each of their team members. We can then
scale grades of individual members based on the feedback they receive.
Those above average get a bump up to plus, those below bump down to minus
or lower. Thoughts?

## 

Greg Kiar gkiar07@gmail.com

On Mon, Jan 25, 2016 at 7:02 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
Brilliant

On Monday, January 25, 2016, Greg Kiar notifications@github.com wrote:

> Each week the students will also fill out an anonymous google form in which
> they rate from 1-10 themselves and each of their team members. We can then
> scale grades of individual members based on the feedback they receive.
> Those above average get a bump up to plus, those below bump down to minus
> or lower. Thoughts?
> 
> ## 
> 
> Greg Kiar <gkiar07@gmail.com
> <javascript:_e(%7B%7D,'cvml','gkiar07@gmail.com');>>
> 
> On Mon, Jan 25, 2016 at 7:02 PM, joshua vogelstein <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> 
> > wrote:
> > 
> > re: grading, i'm open to your proposed system, i don't quite understand
> > it.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Upward-Spiral-Science/Syllabus/issues/1#issuecomment-174737245
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/Syllabus/issues/1#issuecomment-174776144
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by gkiar** [comment]
Added peer evaluation section and link to survey in syllabus under assignments. Will share the survey responses with you privately
