### ISSUE TITLE
create project descriptions

### ISSUE THREAD

**Issue by jovo** [Upward-Spiral-Science/Syllabus#2]
we are going to provide projects.
the ones i am planning are:
- 3D distribution of synapses in cortex
- cortical gene expression synapse diversity
- does processing all brains using the same pipeline improve inference 
- amen data
- semipar-cci on old data

@gkiar can you write a 1 paragraph description of any of them?
either way, please create a md file called 'projects.md' and populate as you can, and then assign to me and i'll do the rest.

**Comment by gkiar** [comment]
Done first pass. Go in and fix/finish?

**Comment by jovo** [comment]
ok, i did mine, can you add a 2-3 ref's for each.
if you don't know them, just assign back to me.

**Comment by gkiar** [comment]
Done, I believe. Close issue when you agree

**Comment by jovo** [comment]
:+1:
